In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import math
import re

import sys
sys.path.append('../../..')
from mount_drive import mount_s_drive

In [2]:
mount_s_drive(subfolder='LCICM/Databases/eICU')

Password for mbranda1: ········

Mounting S drive subfolder LCICM/Databases/eICU
The following files and folders have been mounted to /home/idies/workspace/SAFE/:
  lab.csv
  respiratoryCharting.csv
  nurseCharting.csv
  patient.csv
  apacheApsVar.csv
  respiratoryCare.csv
  vitalPeriodic.csv
  carePlanEOL.csv
  nurseAssessment.csv
  infusionDrug.csv
  hospital.csv
  nurseCare.csv
  carePlanInfectiousDisease.csv
  physicalExam.csv
  carePlanGoal.csv
  admissionDx.csv
  carePlanCareProvider.csv
  medication.csv
  note.csv
  customLab.csv
  vitalAperiodic.csv
  apachePatientResult.csv
  carePlanGeneral.csv
  intakeOutput.csv
  admissionDrug.csv
  pastHistory.csv
  treatment.csv
  apachePredVar.csv
  allergy.csv
  diagnosis.csv
  microLab.csv

mkdir: cannot create directory '/home/idies/workspace/SAFE/': File exists

In [3]:
database_folder = '/home/idies/workspace/SAFE/'

In [4]:
patients_df = pd.read_csv(database_folder+'patient.csv')

In [7]:
patients_df = pd.read_csv(database_folder+'intakeOutput.csv')

In [39]:
# print(patients_df.celllabel.unique().tolist())

['Bodyweight (lb)', 'Bodyweight (kg)', 'P.O.', 'Volume (mL)-sodium chloride 0.9 % flush IVPB 500 mL', 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 20 mEq infusion', 'Urine', 'I.V.', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #2 Mid', 'Saline Flush (mL)', 'Output (ml)-Nephrostomy Left', 'Volume (ml) Amiodarone', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Left Ventriculostomy', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Right Ventriculostomy', 'Volume-Transfuse cryoprecipitate', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #1 Left Lateral', 'Tube Feeding Flush (mL)', 'Tube Feeding Residual Discarded (mL)', 'Volume (ml) Pantoprazole', 'Volume (mL)-sodium chloride 0.9% infusion', 'Volume (ml) Furosemide', 'Volume (ml) Heparin', 'Volume (mL)-potassium chloride 20 mEq/100mL IVPB premix', 'Volume (ml) Diltiazem', 'Volume (mL)-vancomycin 1,250 mg in sodium chloride 0.9% 250 mL IVPB', 'Volume (mL)-meropenem (MERREM) 500 mg in sodium chloride 0.9 % 100 mL IVPB', 'Output (mL)-Y Chest Tube 1 and 2 1 Left Anterior 28 fr 2 Right Mid Pleural collection system', 'Volume (mL)-dextrose 5 % infusion', 'Volume (ml) Fentanyl', 'Volume (ml) Vasopressin', 'Volume (mL) Norepinephrine', 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 1,000 mL', 'Volume-Transfuse red blood cells', 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 750 mg', 'Volume Given (mL)', '8 Hr Total Fluid Removed ', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral b #1 Left Lateral', 'Volume (ml) Dobutamine', 'Volume (ml) Propofol', 'Volume (mL)-dextrose 10 % infusion', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Right Codman', 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Output (mL)-Ostomy-GU Urostomy', 'Volume (ml) 3% NaCl', 'Volume (ml) Dexmedetomidine', 'Volume (ml) Nicardipine', 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 500 mL', 'Output (ml)-Chest Tube #1 Right', 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% infusion', 'Volume Infused  (mL)', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #1 Left', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Right', 'Volume (mL)-lactated ringers infusion', 'Emesis', 'Volume (mL)-sodium chloride 0.9 % with KCl 40 mEq infusion', 'Output (ml)-Chest Tube Right', 'Output (ml)-Chest Tube Left', 'Output Y (ml)-Chest Tube Y - a #1 Right b #2 Left', 'Output Y (ml)-Chest Tube Y - a #1 Anterior b #2 Left', 'Output (ml)-Chest Tube #1 Left', 'Volume (ml) Insulin', 'Volume (ml) Isoproterenol', 'Output Y (ml)-Chest Tube Y - a #1 Right b #1 Left', 'Volume Infused (ml)-HYDROmorphone (DILAUDID) 0.4 mg/mL in sodium chloride 0.9% 30 mL PCA infusion', 'Output (ml)-Chest Tube #1 Pleural Left Lower;Anterior', 'Volume (mL)-sodium chloride 0.45 % infusion', 'Volume (mL)-levETIRAcetam (KepPRA) 500 mg in sodium chloride 0.9 % 100 mL IVPB', 'Volume (mL)-magnesium sulfate 1 g in dextrose 5% 100 mL IVPB premix', 'Output (mL)-External Urethral Device Condom catheter', 'Stool', 'Volume (mL)-sodium chloride 0.9 % with KCl 20 mEq infusion', 'Output Y (ml)-Chest Tube Y - a #1 Anterior b #2 Left Lateral', 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 40 mEq infusion', 'Volume Octreotide', 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5% 1000 mL infusion', 'Volume (ml) Epinephrine', 'Volume (ml) Phenylephrine', 'Output Y (ml)-Chest Tube Y - a #1 Left Mid b #2 Right Mid c #3  ', 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL IVPB', 'Volume (mL)-lactated ringers bolus 500 mL', 'Volume (mL)-metroNIDAZOLE (FLAGYL) IVPB 500 mg', 'Volume (mL)-ceFAZolin (ANCEF) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Volume-Transfuse plasma', 'Volume (ml) Midazolam', 'Volume (mL)-dextran 40 in dextrose 5% (DEXTRAN 40 IN D5W) 10 % infusion', 'Volume (mL)-ceFAZolin 2,000 mg in sodium chloride 0.9% 100 mL IVPB', 'Output Y (ml)-Chest Tube Y - a #1 Right Mid b #2 Left Mid', 'Output (mL)-Straight Catheter', 'Lorazepam Volume', 'Volume (mL)-albumin human 5 % injection 25 g', 'Output (ml)-Ostomy - GI Ileostomy RLQ', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral b #4 Left Lateral', 'Output Y (ml)-Chest Tube Y - a #2 Mid;Anterior b #3 Mid;Anterior', 'Output Y (ml)-Chest Tube Y - a #1 Right Mid b #1 Left Mid', 'Output (ml)-Chest Tube #1 Right Upper', 'Volume-Transfuse platelet pheresis', 'Output (mL)-Y Chest Tube 1 and 2 1 Right 28 fr 2 Left Pleural collection system', 'External Ventricular Drain (EVD) Output (ml)-ICP/External Ventricular Drain (EVD) Right Ventriculostomy', 'Volume (mL)-sodium chloride 0.9 % flush IVPB 250 mL', 'Volume (mL)-ampicillin-sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB', 'Estimated Blood Loss', 'Output (ml)-Chest Tube #2 Left', 'Output Y (ml)-Chest Tube Y - a #1 Right b #2 Mid c #3 Left', 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL IVPB', 'Volume (mL)-vancomycin 1,500 mg in sodium chloride 0.9% 250 mL IVPB', 'Output (mL)-Urinary Catheter Indwelling', 'Volume (ml) Milrinone', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #2 Left', 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with magnesium sulfate 5 g infusion', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #2 Left Anterior', 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion', 'Volume (ml) Dopamine', 'Output (mL)-Y Chest Tube 1 and 2 1 Right 24 fr 2 Left Pleural collection system', 'Volume (mL)-aztreonam (AZACTAM) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Output Y (ml)-Chest Tube Y -  b #2 Right Mid c #3 Left Mid', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Ventriculostomy', 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 20 mEq infusion', 'Output (ml)-Chest Tube #1 Mediastinal Mid', 'Output Y (ml)-Chest Tube Y - a #1 Right Mid b #2 Left Lateral', 'Volume (mL)-lactated ringers bolus 1,000 mL', 'Output (mL)-[REMOVED] Straight Catheter', 'Volume (mL)-ceFEPIme (MAXIPIME) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Balance this Exchange (mL)', 'Output (ml)-Ostomy - GI Colostomy LUQ', 'GI Tube Output (mL)-GI Tube Right', 'Output Y (ml)-Chest Tube Y - a #1 Right Anterior b #2 Mid c #3 Left Anterior', 'Output Y (ml)-Chest Tube Y - a #2 Mid b #2 Mid c #2 Mid', 'Volume (ml) Lipids', 'Output (mL)-Y Chest Tube 3 and 4 3 Mid 32 Fr. 4 Mid 24 Fr. Pleural collection system', 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with potassium chloride 40 mEq, magnesium sulfate 5 g infusion', 'Volume (mL)-albumin human 5 % injection', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral b #2 Left Lateral', 'Output (ml)-Chest Tube #1 Left Lateral', 'Volume (ml) Naloxone', 'Volume (ml) Nitroglycerin', 'Thoracentesis Output', 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN Pyxis Override', 'Volume (ml) Nitroprusside', 'Output (ml)-Chest Tube #1 Pleural Right Anterior', 'Output (mL)-Y Chest Tube 1 and 2 Right Mid 24 fr Left Mid Pleural collection system', 'Volume (ml) Lidocaine', 'External Ventricular Drain (EVD) Output (ml)-ICP/External Ventricular Drain (EVD) Left Ventriculostomy', 'Volume Eptifibatide', 'Output (ml)-Nephrostomy Right', 'Output (ml)-Chest Tube #1 Pleural Right Lower;Anterior', 'Volume (mL)-micafungin (MYCAMINE) 100 mg in sodium chloride 0.9 % 100 mL IVPB', 'Volume (ml) Epoprostenol', 'Volume (mL)-piperacillin-tazobactam (ZOSYN) in dextrose 5% premix IVPB 3.375 g', 'Output Y (ml)-Chest Tube Y - a #2 Right Mid b #2 Left Mid', 'Output Y (ml)-Chest Tube Y - a #2 Right Mid;Anterior b #3 Left Mid;Anterior', 'Output Y (ml)-Chest Tube Y - a #1 Right Mid;Anterior b #2 Left Mid;Anterior', 'Output (ml)-Chest Tube #1 Pleural Right Anterior;Lower', 'Volume (mL)-potassium chloride 20 MEQ/50ML IVPB premix 20 mEq', 'Output (ml)-Chest Tube #1 Midaxillary Right Mid', 'Output (ml)-Chest Tube #2 Midaxillary Left Mid;Lateral', 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% with KCl 20 mEq infusion', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #2 Left Lateral', 'Volume (mL)-propofol (DIPRIVAN) IV bolus', 'Output (mL)-Urinary Catheter Suprapubic catheter', 'Output (ml)-Chest Tube #1 Mid', 'Output Y (ml)-Chest Tube Y - a #1 Right b #2 Right Anterior', 'Volume (mL)-magnesium sulfate 2 g in sodium chloride 0.9% IVPB', 'Output (ml)-Chest Tube #1 Pleural Left Anterior;Lower', 'Volume (mL)-meropenem (MERREM) 1 g in sodium chloride 0.9 % 100 mL IVPB', 'Volume (mL)-linezolid (ZYVOX) IVPB 600 mg', 'Volume (mL)-albumin human (SPA) 25 % injection 12.5 g', 'Output (ml)-Chest Tube #1 Right Mid', 'Output (ml)-Chest Tube #1 Mediastinal Mid;Anterior', 'Output (ml)-Chest Tube #2 Pleural Right Anterior;Lower', 'Output Y (ml)-Chest Tube Y - a #1 Right b #1 Mid c #1 Left', 'Output (ml)-Chest Tube #3 Right Mid', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD)', 'Output Y (ml)-Chest Tube Y - a #1 Right Anterior b #2 Left Anterior', 'Output (mL)-Y Chest Tube 1 and 2 1 Mid 24 fr 2 Mid Pleural collection system', 'Output Y (ml)-Chest Tube Y - a #2 Mid b #3 Mid', 'Volume (mL)-albumin human 5 % injection 12.5 g', 'Output (ml)-Chest Tube #3 Right', 'External Ventricular Drain (EVD) Output (ml)-ICP/External Ventricular Drain (EVD) Right Ventriculostomy;Codman', 'Output (mL)-Y Chest Tube 1 and 2 1 Mid 32 fr 2 Left Pleural collection system', 'Volume Infused (ml)-morphine 2 mg/mL in sodium chloride 0.9% 30 mL PCA infusion', 'Output (ml)-Chest Tube #3 Pleural Right Anterior;Lower', 'Output Y (ml)-Chest Tube Y - a #1 Left b #2 Right', 'Output Y (ml)-Chest Tube Y - a #3 Mid b #4 Mid', 'Output (ml)-Chest Tube #1 Pleural Right Lateral', 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in sodium chloride 0.9 % 250 mL IVPB', 'Output Y (ml)-Chest Tube Y - a #1 Right Mid  c #2 Left Mid', 'Volume (mL)-anticoagulant citrate/dextrose formula A (ACD FORMULA A) infusion', 'Output (ml)-Chest Tube #3 Left Lateral', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral b #2 Mid', 'Output (ml)-Chest Tube Right Lateral', 'Output (ml)-Chest Tube #1 Mediastinal', 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 50 mEq infusion', 'Volume Infused (ml)-fentaNYL (SUBLIMAZE) 2 mcg/mL - bupivacaine (SENSORCAINE MPF) 0.125% premix epidural infusion', 'Output (ml)-Chest Tube #2 Pleural Left Lower;Anterior', 'Volume (mL)-nafcillin (NAFCIL) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Output Y (ml)-Chest Tube Y - a #1 Left Mid b #1 Right Mid', 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 250 mL IVPB', 'Output Y (ml)-Chest Tube Y - a #2 Mid b #2 Mid', 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 150 mEq infusion', 'Volume Tresprostinil ', 'Output (mL)-Urinary Catheter  Indwelling', 'Volume (mL)-calcium chloride 100 mEq in sodium chloride 0.9 % 1,000 mL infusion (CRRT with citrate anticoag)', 'Volume (mL)-potassium phosphate 15 mmol in dextrose 5 % 250 mL IVPB', 'Output (ml)-Chest Tube #1 Right Lateral', 'Atracurium Volume', 'Paracentesis Output', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Left', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #2 Right', 'Output (ml)-Chest Tube #1 Pleural Left Lateral', 'Volume (mL)-calcium gluconate 2 g in dextrose 5 % 50 mL IVPB', 'Output (ml)-Chest Tube #1 Midaxillary Left Lateral', 'Output Y (ml)-Chest Tube Y - a #2 Right Mid b #3 Left Mid', 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5 % 1,000 mL infusion', 'Volume (mL)-albumin human (SPA) 25 % injection 25 g', 'Volume (mL)-dextrose 5 % / lactated ringers infusion', 'Volume (mL)-levETIRAcetam (KepPRA) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Volume (ml) Alteplase', 'Output Y (ml)-Chest Tube Y - a #1 Right b #2 Mid Left', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral', 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 500 mg', 'Output Y (ml)-Chest Tube Y - a #1 Right b #4 Left', 'Volume Infused (ml)-fentaNYL 20 mcg/mL in sodium chloride 0.9% 30 mL PCA infusion', 'Output (ml)-Chest Tube Fourth intercostal space;Midaxillary Right', 'Output Y (ml)-Chest Tube Y - a #1 Left Lower b #1 Mid', 'Bumetanide Volume ', 'Volume (ml) Morphine', 'Volume (mL)-vancomycin (VANCOCIN) 1,000 mg in sodium chloride 0.9 % 250 mL IVPB', 'Output (ml)-Chest Tube #2 Mid', 'Output (ml)-Chest Tube Left Lateral', 'Volume (mL)-aztreonam (AZACTAM) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Output (ml)-Chest Tube #1 Pleural Right', 'Output (ml)-Chest Tube #1 Pleural Left Mid', 'Volume (mL)-Dextran 40 in sodium chloride (DEXTRAN 40 IN NS) 10-0.9 % infusion', 'Output Y (ml)-Chest Tube Y - a #1 Mid b #1 Mid', 'Output (ml)-Chest Tube #3 Mediastinal', 'Output (mL)-Y Chest Tube 1 and 2 1 Right 36 fr 2 Left Pleural collection system', 'Output (ml)-Chest Tube #2 Mediastinal Lower;Anterior', 'Volume (mL)-ALBUMIN HUMAN 5 % IV SOLN Pyxis Override', 'Output (ml)-Chest Tube #1 Left Mid', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral b #2 Mid c #3 Left Lateral', 'Output Y (ml)-Chest Tube Y - a #2 Right b #2 Left', 'Volume (ml) Esmolol', 'Volume (mL)-ceFEPIme (MAXIPIME) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Volume (mL)-magnesium sulfate in sterile water 2 g IVPB premix', 'Output (ml)-Drain Right Abdomen Other (comment)', 'Volume (ml) Argatroban', 'EVD Output (ml)-ICP/External Ventricular Drain (EVD) Right Codman;Ventriculostomy', 'Volume (mL)-ampicillin (OMNIPEN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral b #4 Left Lateral;Mid', 'Bivalirudin Volume', 'External Ventricular Drain (EVD) Output (ml)-ICP/External Ventricular Drain (EVD) Ventriculostomy', 'Output (mL)-Y Chest Tube 1 and 2 1 Mid 36 fr 2 Left Pleural collection system', 'Other', 'Output (ml)-Chest Tube #3 Pleural Left', 'Volume (ml) Hydromorphone', 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 250 mL', 'AHC R FENOLDOPAM Volume', 'Output (ml)-Chest Tube #4 Left', 'Volume (mL)-ciprofloxacin (CIPRO) 400 mg in dextrose 5% 200 mL IVPB', 'Output (ml)-Chest Tube #1', 'Output (ml)-Chest Tube #2 Right', 'Output (ml)-Chest Tube #3 Mid', 'Volume (mL)-potassium chloride 20 MEQ/50ML IVPB premix 40 mEq', 'Output (ml)-Ostomy - GI Colostomy LLQ', 'Output (ml)-Chest Tube Mid', 'Volume Infused (ml)-morphine (ASTRAMORPH PF) 100 mcg/mL, bupivacaine PF (SENSORCAINE-MPF) 0.125 % in sodium chloride 0.9 % 100 mL epidural infusion', 'Output Y (ml)-Chest Tube Y - a #1 Right b #2 Mid', 'Output Y (ml)-Chest Tube Y - a #1 Right Lateral;Anterior b #4 Left Anterior;Lateral', 'Volume (mL)-mannitol (OSMITROL) 20 % 25 g IVPB', 'Volume (mL)-clindamycin 900 mg in sodium chloride 0.9% 50 mL IVPB', 'Output (ml)-Chest Tube #1 Midaxillary;Pleural Right', 'Output (ml)-Chest Tube #2 Pleural Right Lower;Anterior', 'Volume (ml) Magnesium Sulfate', 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 100 mL IVPB', 'Output (ml)-Chest Tube #1 Mediastinal Right Lower;Anterior', 'Output (mL)-Y Chest Tube 1 and 2 1 Right 36 fr 2 Mid Pleural collection system', 'Volume (mL)-sodium chloride 0.45 % with KCl 20 mEq infusion', 'Mass Transfusion Volume', 'Volume (ml) Cisatracurium', 'Output Y (ml)-Chest Tube Y - a #1 Right', 'Volume (ml) Labetalol', 'Output Y (ml)-Chest Tube Y - a #1 Anterior b #2 Anterior', 'Volume (mL)-lactated ringers 1,000 mL with potassium chloride 20 mEq infusion', 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 75 mEq infusion', 'Volume (mL)-fluconazole (DIFLUCAN) IVPB 200 mg', 'Output (ml)-Chest Tube #2 Left Lateral', 'Aminocaproic Acid Volume', 'Output (mL)-Y Chest Tube 1 and 2 1 Mid 24 fr 2 Left Pleural collection system', 'Output (mL)-External Urethral Device ', 'Output Y (ml)-Chest Tube Y - a #2 Right Anterior b #3 Left Anterior', 'Output Y (ml)-Chest Tube Y - a #1 Left b #1 Right', 'Output Y (ml)-Chest Tube Y - a #1 Anterior;Mid b #2 Anterior;Mid', 'Output (ml)-Chest Tube #1 Pleural Left', 'Volume (ml) Vecuronium', 'Output Y (ml)-Chest Tube Y - a #2 Mid b #1 Mid', 'Volume (ml) Abciximab', 'GI Tube Output (mL)-GI Tube', 'Output Y (ml)-Chest Tube Y - b #2 Right Mid c #2 Left Mid', 'Output Y (ml)-Chest Tube Y - Left Lateral Right Lateral', 'Volume (mL)-sodium chloride 0.9 % 1,000 mL infusion', 'Volume (mL)-sodium phosphate 15 mmol in dextrose 5 % 250 mL IVPB', 'Output Y (ml)-Chest Tube Y - a #1 Left b #2 Mid c #3 Right', 'Volume (mL)-clindamycin 600 mg in sodium chloride 0.9% 50 mL IVPB', 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 50 mEq infusion', 'Output Y (ml)-Chest Tube Y - a #1 Left b #2 Right c #3', 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 40 mEq infusion', 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 100 mEq infusion', 'Output (ml)-Chest Tube #2 Right Lateral', 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in sodium chloride 0.9 % 250 mL IVPB', 'Output (mL)-Urethral Catheter', 'Volume (mL)-lactated ringers infusion 1,000 mL', 'Free Water', 'TPN/PPN Intake Amount', 'Oral Intake Amount', 'Lipid Intake Amount', 'Drainage Output Amount1', 'IV Intake Amount', 'Number of Bowel Movements Output', 'pRBCs', 'Chest Tube Drainage Output1', 'Number of Incontinent Voids', 'Drainage Output Amount2', 'Drainage Output Amount3', 'Tube Feeding Amount', 'Gastric (NG)', 'Out', 'Albumin Intake', 'FFP', 'Chest Tube Drainage Output2', 'Blood Loss', 'In', 'Other meds', 'Platelets', 'Continuous infusion meds', 'levophed', 'NS ', 'PO fluids', 'Chest Tube', 'PO oral', 'Lido', 'Propofol', 'Enteral feed', 'D5 0.45 NS ', 'D5W  w/75 mEq NaHCO3 1000 ml', 'zosyn', 'precedex', 'JP 1', 'JP 3', 'Enteral Nutren 1.5', 'heparin', 'Levo', 'insulin', 'PRECEDEX', 'VASO', 'HEPARIN', 'INSULIN', 'LEVOPHED', 'VASSOPRESSIN', 'VERSED', 'KCL', 'foley', 'jp', 'EBL', 'Zosyn', 'MED CT X2', 'LEVO', 'argatroban', 'Enteral Fibersource', 'Amiodarone', 'Cardizem', 'Enteral NUTREN 1.5', 'Levophed', 'Insulin drip', 'Protonix ', '0.45 NS ', 'FOLEY', 'Heparin', 'Cardene', 'JP', 'Enteral flush ', 'AMIODORONE GTT', 'fentanyl', 'VASOPRESSIN', 'versed', 'PO intake', 'Heparin Drip', 'Vasopressin', 'PO Fluids', 'Enteral FLUSH/MEDS', 'Enteral TF', 'CRRT FLUSH', 'Fentanyl drip', 'SANDOSTATIN', 'Versed', 'CRRT- UF removed', 'EVD', 'Amicar', 'cardizem', 'DIPRIVAN', 'amiodarone', 'Enteral fibersource', 'Enteral Water flush', 'TPN', 'NS', 'cardene', 'LR ', 'Insulin', '0.45 NS  w/20 mEq KCL 1000 ml', 'PROPOFOL', 'Enteral Novasource Renal', 'CRRT - UF removed', 'Neosynephrine', 'Enteral water flush', 'D5W  w/150 mEq NaHCO3', 'Magnesium', 'D5W ', 'diprivan', 'Enteral FLUSH', 'Milrinone', 'HEPARIN DRIP', 'Protonix gtt', 'Sandostatin gtt', 'Nimbex', 'Fentanyl', 'Argatroban', 'Enteral water flushes', 'Foley', 'Enteral NOVASOURCE RENAL', 'D5NS ', 'propofol', 'Enteral fibersource HN', 'D5NS  w/20 mEq KCL 1000 ml', 'Enteral Vivonex', 'Enteral nutren 1.5', 'Dilaudid drip', 'Fibersource ', 'Propofol drip', 'Enteral Flushes', 'Enteral TUBE FEED', 'PO po', 'KEPPRA', 'Enteral WATER FLUSHES', 'Enteral flush', 'Dobutamine', 'Enteral Peptamen AF', 'Enteral WATER FLUSH', 'Enteral FEED', 'Lasix', 'Precedex', 'D5 NS', 'Zyvox', 'Levophed gtt', 'Propofol gtt', 'PO', 'Dobutrex', 'Enteral H2O', 'Norepinephrine', 'KPhos', 'ABX', 'PO fluid', 'Hypertonic saline 3% ', 'PO liquids', 'PO Fluid', 'NS  w/20 mEq KCL', 'PO WATER', 'Enteral Peptamen', 'Dopamine', 'Veletri', 'cardizem drip', 'D5W  w/20 mEq KCL', 'Flagyl', 'AMIO', 'D5 0.45 NS  w/20 mEq KCL', 'PO clear liquid', 'Epinephrine', 'Ofirmev', 'D5 0.45 NS  w/40 mEq KCL 1000 ml', 'Protonix', '0.45 NS  w/20 mEq KCL', 'Enteral Nutren', 'Primacor', 'Enteral Water flushes', 'Neo', 'LEvophed', 'MERREM', 'NS KVO', 'Main IVF', 'PO PO FLUIDS', 'D5 0.45 NS  w/20 mEq KCL 1000 ml', 'milrinone', 'Levophed drip', '5% Albumin', 'Enteral Fibersource HN', 'ZOSYN', 'Enteral tube feeding', 'PO po fluids', 'FENTANYL', 'Enteral Fluids', 'D10W', 'PO Flush/ Meds', 'Enteral h20 flush', 'JP drain', 'Enteral Feeds', 'CRRT flush', 'Enteral H2O flushes', 'Sandostatin', 'Enteral Flush', 'Enteral ngt', 'Diprivan', 'OGT', 'NIMBEX', 'TPA', 'Colostomy', 'Heparin gtt', 'Enteral Tube Fee

In [71]:
patients_df

,intakeoutputid,patientunitstayid,intakeoutputoffset,intaketotal,outputtotal,dialysistotal,nettotal,intakeoutputentryoffset,cellpath,celllabel,cellvaluenumeric,cellvaluetext
0,9301638,205505,661,0.00,0.0,0.0,0.00,661,flowsheet|Flowsheet Cell Labels|I&O|Weight|Bod...,Bodyweight (lb),238.20,238.20
1,9301639,205505,661,0.00,0.0,0.0,0.00,661,flowsheet|Flowsheet Cell Labels|I&O|Weight|Bod...,Bodyweight (kg),108.00,108.00
2,9301642,150708,3523,727.00,0.0,0.0,727.00,3523,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,P.O.,200.00,200.00
3,9301643,150708,3523,727.00,0.0,0.0,727.00,3523,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,Volume (mL)-sodium chloride 0.9 % flush IVPB 5...,527.00,527.00
4,9301645,158159,24801,120.00,0.0,0.0,120.00,24801,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,P.O.,120.00,120.00
...,...,...,...,...,...,...,...,...,...,...,...,...
12030284,219417610,3335854,1140,152.10,0.0,0.0,152.10,1140,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,Crystalloids,152.10,152.10
12030285,219417636,3334548,766,340.00,350.0,0.0,-10.00,766,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,Crystalloids,100.00,100.00
12030286,219417643,3330152,5102,300.00,0.0,0.0,300.00,5102,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,Nutrition Total,300.00,300.00
12030287,219417653,3327194,3834,101.18,55.0,0.0,46.18,3834,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,Crystalloids,101.18,101.18
12030288,219417654,3327194,3834,101.18,55.0,0.0,46.18,3834,flowsheet|Flowsheet Cell Labels|I&O|Output (ml...,OtherDrainTotal,55.00,55.00

In [8]:
patients_df = pd.read_csv(database_folder+'patient.csv')

In [8]:
patients_df.columns

Index(['patientunitstayid', 'patienthealthsystemstayid', 'gender', 'age',
       'ethnicity', 'hospitalid', 'wardid', 'apacheadmissiondx',
       'admissionheight', 'hospitaladmittime24', 'hospitaladmitoffset',
       'hospitaladmitsource', 'hospitaldischargeyear',
       'hospitaldischargetime24', 'hospitaldischargeoffset',
       'hospitaldischargelocation', 'hospitaldischargestatus', 'unittype',
       'unitadmittime24', 'unitadmitsource', 'unitvisitnumber', 'unitstaytype',
       'admissionweight', 'dischargeweight', 'unitdischargetime24',
       'unitdischargeoffset', 'unitdischargelocation', 'unitdischargestatus',
       'uniquepid'],
      dtype='object')

In [9]:
patients_df['patientunitstayid'].nunique()

200859

In [10]:
patients_df['uniquepid'].nunique()

139367

In [6]:
myIds = pd.read_csv('../../../Isalis/eICU/eICU_patientunitstayids.txt', header = None)
myIds

              0
0      142723.0
1      145204.0
2      145205.0
3      145830.0
4      146619.0
...         ...
3400  3352445.0
3401  3352512.0
3402  3352727.0
3403  3353194.0
3404  3353251.0

[3405 rows x 1 columns]

In [16]:
patients_df = patients_df[patients_df['patientunitstayid'].isin(myIds[0])]

In [17]:
(patients_df.head(1).to_string())

'     patientunitstayid  patienthealthsystemstayid  gender age  ethnicity  hospitalid  wardid                                                                                   apacheadmissiondx  admissionheight hospitaladmittime24  hospitaladmitoffset hospitaladmitsource  hospitaldischargeyear hospitaldischargetime24  hospitaldischargeoffset hospitaldischargelocation hospitaldischargestatus      unittype unitadmittime24 unitadmitsource  unitvisitnumber unitstaytype  admissionweight  dischargeweight unitdischargetime24  unitdischargeoffset unitdischargelocation unitdischargestatus  uniquepid\n220             142723                     130115  Female  68  Caucasian          58     108  Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System)            165.1            21:48:29                 -615               Floor                   2015                19:07:00                     2104            Other External                   Alive  Med-Surg ICU        08:03:00           Floor                1        admit             50.3             50.3            18:13:00                 2050  Step-Down Unit (SDU)               Alive  002-40742'

In [131]:
myPredictorsDf = patients_df[['patientunitstayid', 'gender', 'age', 'apacheadmissiondx', 'admissionheight', 'hospitaladmittime24', 'hospitaladmitsource', 'admissionweight']]

### Cardiac Arrest

In [7]:
diagnosis_df = pd.read_csv(database_folder+'treatment.csv')

In [8]:
diagnosis_df = diagnosis_df[diagnosis_df['patientunitstayid'].isin(myIds[0])]

In [14]:
diagnosis_df[diagnosis_df.treatmentoffset < 360]

,treatmentid,patientunitstayid,treatmentoffset,treatmentstring,activeupondischarge
3691,9283553,244718,27,pulmonary|ventilation and oxygenation|oxygen t...,False
3695,10039992,244718,27,gastrointestinal|medications|stress ulcer prop...,False
3698,8655840,244718,27,pulmonary|medications|neuromuscular blocking a...,False
3703,9815159,244718,27,cardiovascular|ventricular dysfunction|vasodil...,False
3705,9859885,244718,27,pulmonary|ventilation and oxygenation|mechanic...,False
...,...,...,...,...,...
3688736,82519109,3353251,108,pulmonary|radiologic procedures / bronchoscopy...,False
3688738,82261667,3353251,291,cardiovascular|arrhythmias|antiarrhythmics|cla...,False
3688739,82299003,3353251,291,cardiovascular|shock|inotropic agent|norepinep...,False
3688740,82519717,3353251,291,pulmonary|radiologic procedures / bronchoscopy...,False
3688741,82608952,3353251,291,pulmonary|ventilation and oxygenation|mechanic...,False

In [17]:
diagnosis_df.treatmentstring.iloc[895]

'cardiovascular|non-operative procedures|diagnostic ultrasound of heart'

In [85]:
diagnosis_df

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority,10-19 % of body surface,1:2 conduction,20-29 % of body surface,...,with vomiting,without foley catheter,without gangrene,without hemodynamic compromise,without return to pre-existing conscious level,"witnessed, < 15 minutes CPR","witnessed, > 15 minutes CPR",wound dehiscence,wound infection,wound-associated
895,3872672,142723,True,143,cardiovascular|cardiac arrest|cardiac arrest,"427.5, I46.9",Primary,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2307,4198269,145204,False,3,toxicology|drug overdose|ethanol overdose|with...,T51.0,Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2308,4058516,145204,False,3,renal|electrolyte imbalance|hypokalemia|severe...,"276.8, E87.6",Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2309,3975271,145204,False,3,cardiovascular|cardiac arrest|cardiac arrest,"427.5, I46.9",Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2310,3624338,145204,False,3,cardiovascular|shock / hypotension|hypotension,"458.9, I95.9",Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2710664,46097425,3353251,False,4080,cardiovascular|chest pain / ASHD|acute coronar...,"410.90, I21.3",Major,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2710665,46330136,3353251,False,4080,renal|disorder of urinary tract / renal system...,"599.0, N39.0",Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2710666,46330880,3353251,False,2653,renal|disorder of urinary tract / renal system...,"599.0, N39.0",Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2710667,46330138,3353251,False,11304,renal|disorder of urinary tract / renal system...,"599.0, N39.0",Other,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2710668,46150971,3353251,False,4080,cardiovascular|shock / hypotension|sepsis,"038.9, A41.9",Major,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
one_hot = one_hot.add_prefix('treatment_')

In [37]:
one_hot.columns

Index(['treatment_10-15 cm H2O', 'treatment_25-30%', 'treatment_30-40%',
       'treatment_40-50%', 'treatment_5-10 cm H2O', 'treatment_50-60%',
       'treatment_500-1000 ml', 'treatment_60-70%', 'treatment_70-80%',
       'treatment_80-90%',
       ...
       'treatment_with irrigation', 'treatment_with stent placement',
       'treatment_with stenting', 'treatment_with suction',
       'treatment_with thrombolysis',
       'treatment_with transbronchial lung biopsy',
       'treatment_without IV contrast', 'treatment_without contrast',
       'treatment_wound care', 'treatment_wounds / temperature'],
      dtype='object', length=816)

In [41]:
filtered

,treatment_treatmentid,treatment_treatmentoffset,treatment_activeupondischarge,treatment_10-15 cm H2O,treatment_25-30%,treatment_30-40%,treatment_40-50%,treatment_5-10 cm H2O,treatment_50-60%,treatment_500-1000 ml,...,treatment_with stent placement,treatment_with stenting,treatment_with suction,treatment_with thrombolysis,treatment_with transbronchial lung biopsy,treatment_without IV contrast,treatment_without contrast,treatment_wound care,treatment_wounds / temperature,patientunitstayid
0,84583959,243,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,244718
1,114921597,3107,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,246179
2,117125377,2378,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,249143
3,66781357,42,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,250724
4,325241745,8939,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,251469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2895,577597569,1124,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3352437
2896,577157903,609,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3352512
2897,1071558496,3276,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,3352727
2898,164849002,104,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3353194
2899,824465309,2046,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3353251

In [42]:
myPredictorsDf1 = myPredictorsDf.merge(filtered[['patientunitstayid'] + list(one_hot.columns)], on=['patientunitstayid'], how='left')

In [43]:
myPredictorsDf1

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,...,treatment_with irrigation,treatment_with stent placement,treatment_with stenting,treatment_with suction,treatment_with thrombolysis,treatment_with transbronchial lung biopsy,treatment_without IV contrast,treatment_without contrast,treatment_wound care,treatment_wounds / temperature
0,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3401,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3402,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3403,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3404,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
filtered = diagnosis_df[(diagnosis_df.treatmentoffset > 0) & (diagnosis_df.treatmentoffset < 360)].groupby('patientunitstayid').agg('sum').reset_index()

/tmp/ipykernel_171/963208165.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  filtered = diagnosis_df[(diagnosis_df.treatmentoffset > 0) & (diagnosis_df.treatmentoffset < 360)].groupby('patientunitstayid').agg('sum').reset_index()

In [24]:
filtered[one_hot.columns] = (filtered[one_hot.columns] != 0).astype(int)

In [25]:
filtered

,patientunitstayid,treatmentid,treatmentoffset,activeupondischarge,10-15 cm H2O,25-30%,30-40%,40-50%,5-10 cm H2O,50-60%,...,with irrigation,with stent placement,with stenting,with suction,with thrombolysis,with transbronchial lung biopsy,without IV contrast,without contrast,wound care,wounds / temperature
0,244718,84583959,243,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,246179,114921597,3107,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,249143,117125377,2378,8,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,250724,66781357,42,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,251469,325241745,8939,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2895,3352437,577597569,1124,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2896,3352512,577157903,609,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2897,3352727,1071558496,3276,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2898,3353194,164849002,104,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2899,3353251,824465309,2046,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
filtered = filtered.add_prefix("treatment_")

In [29]:
filtered['patientunitstayid'] = filtered.treatment_patientunitstayid
filtered.drop(columns=['treatment_patientunitstayid'],inplace=True)

In [18]:
diagnosis_df['conditions'] = diagnosis_df['treatmentstring'].str.split('|')
one_hot = diagnosis_df['conditions'].explode().str.get_dummies().groupby(level=0).sum()
diagnosis_df = diagnosis_df.drop(columns=['conditions']).join(one_hot)

In [26]:
diagnosis_df[one_hot.columns].loc[:, diagnosis_df[one_hot.columns].sum() > 60]

,10-15 cm H2O,30-40%,40-50%,5-10 cm H2O,50-60%,>90%,ACE inhibitor,C V V H,C V V H D,CABG,...,vitamin K,volume controlled,with angioplasty,with bronchial alveolar lavage,with contrast,with stent placement,with suction,without contrast,wound care,wounds / temperature
3687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3690,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3688737,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3688738,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3688739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3688740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3688741,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [132]:
myPEA = diagnosis_df[diagnosis_df.diagnosisstring.str.contains('pulseless electrical activity')]

In [133]:
myAsystole = diagnosis_df[diagnosis_df.diagnosisstring.str.contains('asystole')]

In [134]:
myVentricularTachycardia = diagnosis_df[diagnosis_df.diagnosisstring.str.contains('ventricular tachy')]

In [135]:
myVentricularFibrilation = diagnosis_df[diagnosis_df.diagnosisstring.str.contains('ventricular fibrillation')]

In [136]:
myPredictorsDf['PEA'] = 0
myPredictorsDf.loc[myPredictorsDf.patientunitstayid.isin(myPEA.patientunitstayid), 'PEA'] = 1
myPredictorsDf.PEA.sum()

/tmp/ipykernel_173/3371880830.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myPredictorsDf['PEA'] = 0

595

In [137]:
myPredictorsDf['Asystole'] = 0
myPredictorsDf.loc[myPredictorsDf.patientunitstayid.isin(myAsystole.patientunitstayid), 'Asystole'] = 1
myPredictorsDf.Asystole.sum()

/tmp/ipykernel_173/362054599.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myPredictorsDf['Asystole'] = 0

314

In [138]:
myPredictorsDf['VTachy'] = 0
myPredictorsDf.loc[myPredictorsDf.patientunitstayid.isin(myVentricularTachycardia.patientunitstayid), 'VTachy'] = 1
myPredictorsDf.VTachy.sum()

/tmp/ipykernel_173/302759635.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myPredictorsDf['VTachy'] = 0

219

In [139]:
myPredictorsDf['VFib'] = 0
myPredictorsDf.loc[myPredictorsDf.patientunitstayid.isin(myVentricularFibrilation.patientunitstayid), 'VFib'] = 1
myPredictorsDf.VFib.sum()

/tmp/ipykernel_173/801951469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myPredictorsDf['VFib'] = 0

383

In [10]:
file_path = database_folder+'nurseCharting.csv'
chunk_size = 1e6

# patient_unit_stay_ids = ca_patients_df['patientunitstayid']
df_chunks = []

num_chunks = 0
for chunk in pd.read_csv(file_path,chunksize=chunk_size):
    filtered_chunk = chunk[chunk['patientunitstayid'].isin(myIds[0])]
    df_chunks.append(filtered_chunk)
    if num_chunks % 10 == 0:
        print(f'Chunk {num_chunks} Processed.')
    num_chunks += 1
    del chunk

nurse_charting_df = pd.concat(df_chunks, ignore_index=True)
print('Processing finished.')

Chunk 0 Processed.
Chunk 10 Processed.
Chunk 20 Processed.
Chunk 30 Processed.
Chunk 40 Processed.
Chunk 50 Processed.
Chunk 60 Processed.
Chunk 70 Processed.
Chunk 80 Processed.
Chunk 90 Processed.
Chunk 100 Processed.
Chunk 110 Processed.
Chunk 120 Processed.
Chunk 130 Processed.
Chunk 140 Processed.
Chunk 150 Processed.
Processing finished.

In [141]:
nurse_charting_df.patientunitstayid.nunique()

3405

In [142]:
myDfTempC = nurse_charting_df[(nurse_charting_df.nursingchartcelltypevalname == 'Temperature (F)')]
myDfTempC.nursingchartvalue = myDfTempC.nursingchartvalue.astype(float)
myDfTempC.sort_values(by=['patientunitstayid', 'nursingchartentryoffset'], inplace=True)
myDfTempC['TimeDiff'] = myDfTempC['nursingchartoffset'].diff()
myDfTempC['TempTimesTime'] = myDfTempC['TimeDiff'] * myDfTempC['nursingchartvalue'].shift(1)
myDfTempC['RollingTemp'] = myDfTempC['TempTimesTime'].rolling(window=2).sum()
myDfTempC['RollingTime'] = myDfTempC['TimeDiff'].rolling(window=2).sum()
myDfTempC['AvgTemp'] = myDfTempC['RollingTemp'] / myDfTempC['RollingTime']
myDfTempC[['TempTimesTime', 'TimeDiff', 'nursingchartvalue', 'RollingTemp', 'RollingTime', 'AvgTemp']]
myDfTempC2 = myDfTempC[(myDfTempC.nursingchartentryoffset < 2000)  \
        & (myDfTempC.AvgTemp < 94.1)
        & (myDfTempC.AvgTemp > 88.7)]
print(myDfTempC2.nunique())
myDfTempC2['nursingchartentryoffset2'] = myDfTempC2['nursingchartentryoffset']
myHyp2 = myDfTempC2.groupby('patientunitstayid').agg({'patientunitstayid':'count', 'nursingchartvalue': 'min', 'nursingchartentryoffset':'min', 'nursingchartentryoffset2':'max'})
myHyp2['Hyp'] = (myHyp2['patientunitstayid'] > 12).astype(int) \
                & (myHyp2['nursingchartvalue'] > 77).astype(int) \
                & (myHyp2['nursingchartentryoffset'] > 0).astype(int)\
                & (myHyp2['nursingchartentryoffset2'] - myHyp2['nursingchartentryoffset'] > 720).astype(int)
myHyp2.Hyp.sum()

nursingchartid                  30056
patientunitstayid                1313
nursingchartoffset               2290
nursingchartentryoffset          2276
nursingchartcelltypecat             1
nursingchartcelltypevallabel        1
nursingchartcelltypevalname         1
nursingchartvalue                 209
TimeDiff                          598
TempTimesTime                    3490
RollingTemp                      7671
RollingTime                       851
AvgTemp                          4575
dtype: int64

/tmp/ipykernel_173/2035616874.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC.nursingchartvalue = myDfTempC.nursingchartvalue.astype(float)
/tmp/ipykernel_173/2035616874.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC.sort_values(by=['patientunitstayid', 'nursingchartentryoffset'], inplace=True)
/tmp/ipykernel_173/2035616874.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['TimeDiff'] = myDfTempC['nursingchartoffset'].diff()
/tmp/ipykernel_173/2035616874.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['TempTimesTime'] = myDfTempC['TimeDiff'] * myDfTempC['nursingchartvalue'].shift(1)
/tmp/ipykernel_173/2035616874.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['RollingTemp'] = myDfTempC['TempTimesTime'].rolling(window=2).sum()
/tmp/ipykernel_173/2035616874.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['RollingTime'] = myDfTempC['TimeDiff'].rolling(window=2).sum()
/tmp/ipykernel_173/2035616874.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['AvgTemp'] = myDfTempC['RollingTemp'] / myDfTempC['RollingTime']
/tmp/ipykernel_173/2035616874.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC2['nursingchartentryoffset2'] = myDfTempC2['nursingchartentryoffset']

587

In [28]:
myDfTempC = nurse_charting_df[(nurse_charting_df.nursingchartcelltypevalname == 'Temperature (C)')]
myDfTempC.nursingchartvalue = myDfTempC.nursingchartvalue.astype(float)
myDfTempC.sort_values(by=['patientunitstayid', 'nursingchartentryoffset'], inplace=True)
myDfTempC['TimeDiff'] = myDfTempC['nursingchartoffset'].diff()
myDfTempC['TempTimesTime'] = myDfTempC['TimeDiff'] * myDfTempC['nursingchartvalue'].shift(1)
myDfTempC['RollingTemp'] = myDfTempC['TempTimesTime'].rolling(window=2).sum()
myDfTempC['RollingTime'] = myDfTempC['TimeDiff'].rolling(window=2).sum()
myDfTempC['AvgTemp'] = myDfTempC['RollingTemp'] / myDfTempC['RollingTime']
myDfTempC[['TempTimesTime', 'TimeDiff', 'nursingchartvalue', 'RollingTemp', 'RollingTime', 'AvgTemp']]
myDfTempC2 = myDfTempC[(myDfTempC.nursingchartentryoffset < 2880)  \
        & (myDfTempC.nursingchartentryoffset > 0)
        & (myDfTempC.nursingchartvalue < 36)]
# print(myDfTempC2.nunique())
myDfTempC2['nursingchartentryoffset2'] = myDfTempC2['nursingchartentryoffset']
myHyp = myDfTempC2.groupby('patientunitstayid').agg({'patientunitstayid':'count', 'nursingchartvalue': 'min', 'nursingchartentryoffset':'min', 'nursingchartentryoffset2':'max'})
myHyp['Hyp'] = (myHyp['patientunitstayid'] > 20).astype(int) \
                & (myHyp['nursingchartvalue'] > 27).astype(int) \
                & (myHyp['nursingchartentryoffset2'] - myHyp['nursingchartentryoffset'] > 720).astype(int)
myHyp[myHyp['Hyp'] == 1]

/tmp/ipykernel_216/2591700911.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC.nursingchartvalue = myDfTempC.nursingchartvalue.astype(float)
/tmp/ipykernel_216/2591700911.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC.sort_values(by=['patientunitstayid', 'nursingchartentryoffset'], inplace=True)
/tmp/ipykernel_216/2591700911.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['TimeDiff'] = myDfTempC['nursingchartoffset'].diff()
/tmp/ipykernel_216/2591700911.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['TempTimesTime'] = myDfTempC['TimeDiff'] * myDfTempC['nursingchartvalue'].shift(1)
/tmp/ipykernel_216/2591700911.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['RollingTemp'] = myDfTempC['TempTimesTime'].rolling(window=2).sum()
/tmp/ipykernel_216/2591700911.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['RollingTime'] = myDfTempC['TimeDiff'].rolling(window=2).sum()
/tmp/ipykernel_216/2591700911.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC['AvgTemp'] = myDfTempC['RollingTemp'] / myDfTempC['RollingTime']
/tmp/ipykernel_216/2591700911.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDfTempC2['nursingchartentryoffset2'] = myDfTempC2['nursingchartentryoffset']

,patientunitstayid,nursingchartvalue,nursingchartentryoffset,nursingchartentryoffset2,Hyp
patientunitstayid,,,,,
153418,116,33.0,11,2336,1
161900,32,33.1,351,1971,1
162897,164,27.8,498,2878,1
165286,104,32.4,468,2778,1
166054,135,33.3,259,2584,1
...,...,...,...,...,...
3352203,68,32.6,151,2101,1
3352445,59,33.0,71,2141,1
3352512,105,32.2,22,2512,1
3352727,59,32.9,236,2141,1
3353251,78,32.5,73,1873,1

In [32]:
myPredictorsDf['Hypothermia'] = 0
myPredictorsDf.loc[myPredictorsDf.patientunitstayid.isin(myHyp[myHyp['Hyp'] == 1].index), 'Hypothermia'] = 1
myPredictorsDf[['Hypothermia', 'patientunitstayid']]
myPredictorsDf.Hypothermia.sum()

685

In [30]:
print(myDfTempC[(myDfTempC.patientunitstayid ==3352203) & (myDfTempC.nursingchartentryoffset < 3000)].to_string())

         nursingchartid  patientunitstayid  nursingchartoffset  nursingchartentryoffset nursingchartcelltypecat nursingchartcelltypevallabel nursingchartcelltypevalname  nursingchartvalue  TimeDiff  TempTimesTime  RollingTemp  RollingTime    AvgTemp
5830294      2290228976            3352203                   5                        5             Vital Signs                  Temperature             Temperature (C)               36.3    -147.0        -4880.4      -4382.4       -132.0  33.200000
5830066      2302912033            3352203                  31                       31             Vital Signs                  Temperature             Temperature (C)               36.3      26.0          943.8      -3936.6       -121.0  32.533884
5830271      2307029844            3352203                  91                       91             Vital Signs                  Temperature             Temperature (C)               36.3      60.0         2178.0       3121.8         86.0  36.300000
5831106      2300817197            3352203                 106                      106             Vital Signs                  Temperature             Temperature (C)               36.3      15.0          544.5       2722.5         75.0  36.300000
5831353      2293178383            3352203                 121                      121             Vital Signs                  Temperature             Temperature (C)               36.3      15.0          544.5       1089.0         30.0  36.300000
5830110      2300705538            3352203                 136                      136             Vital Signs                  Temperature             Temperature (C)               36.4      15.0          544.5       1089.0         30.0  36.300000
5831102      2293864890            3352203                 151                      151             Vital Signs                  Temperature             Temperature (C)               35.9      15.0          546.0       1090.5         30.0  36.350000
5830352      2287470350            3352203                 166                      166             Vital Signs                  Temperature             Temperature (C)               35.3      15.0          538.5       1084.5         30.0  36.150000
5831255      2295575984            3352203                 181                      181             Vital Signs                  Temperature             Temperature (C)               34.3      15.0          529.5       1068.0         30.0  35.600000
5831337      2282952222            3352203                 196                      196             Vital Signs                  Temperature             Temperature (C)               33.7      15.0          514.5       1044.0         30.0  34.800000
5831378      2285737363            3352203                 211                      211             Vital Signs                  Temperature             Temperature (C)               33.2      15.0          505.5       1020.0         30.0  34.000000
5830286      2287031140            3352203                 226                      226             Vital Signs                  Temperature             Temperature (C)               32.6      15.0          498.0       1003.5         30.0  33.450000
5830728      2287616945            3352203                 241                      241             Vital Signs                  Temperature             Temperature (C)               32.7      15.0          489.0        987.0         30.0  32.900000
5831436      2281617104            3352203                 256                      256             Vital Signs                  Temperature             Temperature (C)               32.9      15.0          490.5        979.5         30.0  32.650000
5831341      2281141767            3352203                 271                      271             Vital Signs                  Temperature             Temperature (C)               33.1      15.0          493.5        984.0         30.0  32.800000
5831485      2301608653            3352203                 286                      286             Vital Signs                  Temperature             Temperature (C)               33.0      15.0          496.5        990.0         30.0  33.000000
5830119      2299319772            3352203                 301                      301             Vital Signs                  Temperature             Temperature (C)               32.9      15.0          495.0        991.5         30.0  33.050000
5830495      2286861902            3352203                 316                      316             Vital Signs                  Temperature             Temperature (C)               33.0      15.0          493.5        988.5         30.0  32.950000
5830626      2308438578            3352203                 331                      331             Vital Signs                  Temperature             Temperature (C)               33.0      15.0          495.0        988.5         30.0  32.950000
5830183      2295043725            3352203                 361                      361             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1485.0         45.0  33.000000
5830099      2306927722            3352203                 391                      391             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5830147      2281837439            3352203                 451                      451             Vital Signs                  Temperature             Temperature (C)               33.0      60.0         1980.0       2970.0         90.0  33.000000
5830134      2310435065            3352203                 511                      511             Vital Signs                  Temperature             Temperature (C)               33.0      60.0         1980.0       3960.0        120.0  33.000000
5830208      2312316266            3352203                 571                      571             Vital Signs                  Temperature             Temperature (C)               33.0      60.0         1980.0       3960.0        120.0  33.000000
5831145      2289706254            3352203                 631                      631             Vital Signs                  Temperature             Temperature (C)               33.0      60.0         1980.0       3960.0        120.0  33.000000
5830795      2286329218            3352203                 691                      691             Vital Signs                  Temperature             Temperature (C)               33.0      60.0         1980.0       3960.0        120.0  33.000000
5830533      2291938287            3352203                 721                      721             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       2970.0         90.0  33.000000
5830807      2283279022            3352203                 751                      751             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5830079      2303786641            3352203                 781                      781             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5831487      2304227104            3352203                 811                      811             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5830401      2294546107            3352203                 841                      841             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5830885      2281169851            3352203                 871                      871             Vital Signs                  Temperature             Temperature (C)               32.9      30.0          990.0       1980.0         60.0  33.000000
5830340      2292450138            3352203                 901                      901             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          987.0       1977.0         60.0  32.950000
5830349      2305664417            3352203                 931                      931             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1977.0         60.0  32.950000
5830753      2306922742            3352203                 961                      961             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5831074      2301815652            3352203                 991                      991             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5830140      2305224965            3352203                1021                     1021             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          990.0       1980.0         60.0  33.000000
5830901      2281494365            3352203                1051                     1051             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1983.0         60.0  33.050000
5830465      2284767478            3352203                1081                     1081             Vital Signs                  Temperature             Temperature (C)               32.8      30.0          993.0       1986.0         60.0  33.100000
5831331      2291605653            3352203                1111                     1111             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          984.0       1977.0         60.0  32.950000
5831275      2287139045            3352203                1141                     1141             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          990.0       1974.0         60.0  32.900000
5831171      2296490997            3352203                1171                     1171             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1983.0         60.0  33.050000
5830932      2293542443            3352203                1201                     1201             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1986.0         60.0  33.100000
5830590      2291093703            3352203                1231                     1231             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1986.0         60.0  33.100000
5830402      2305260179            3352203                1261                     1261             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1986.0         60.0  33.100000
5830951      2301450267            3352203                1291                     1291             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          993.0       1986.0         60.0  33.100000
5830145      2307713758            3352203                1321                     1321             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1983.0         60.0  33.050000
5830679      2282055197            3352203                1351                     1351             Vital Signs                  Temperature             Temperature (C)               33.0      30.0          990.0       1980.0         60.0  33.000000
5830289      2293015877            3352203                1381                     1381             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          990.0       1980.0         60.0  33.000000
5831511      2305534298            3352203                1411                     1411             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1983.0         60.0  33.050000
5831387      2295556613            3352203                1436                     1436             Vital Signs                  Temperature             Temperature (C)               33.1      25.0          827.5       1820.5         55.0  33.100000
5831264      2286020675            3352203                1471                     1471             Vital Signs                  Temperature             Temperature (C)               33.1      35.0         1158.5       1986.0         60.0  33.100000
5830276      2304164368            3352203                1501                     1501             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       2151.5         65.0  33.100000
5831324      2294493378            3352203                1531                     1531             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1986.0         60.0  33.100000
5830882      2282771166            3352203                1561                     1561             Vital Signs                  Temperature             Temperature (C)               33.1      30.0          993.0       1986.0         60.0  33.100000
5831159      2293333651            3352203                1591                     1591             Vital Signs                  Temperature             Temperature (C)               33.2      30.0          993.0       1986.0         60.0  33.100000
5830470      2285092169            3352203                1621                     1621             Vital Signs                  Temperature             Temperature (C)               33.5      30.0          996.0       1989.0         60.0  33.150000
5831233      2298265984            3352203                1651                     1651             Vital Signs                  Temperature             Temperature (C)               33.7      30.0         1005.0       2001.0         60.0  33.350000
5830070      2306387071            3352203                1681                     1681             Vital Signs                  Temperature             Temperature (C)               33.9      30.0         1011.0       2016.0         60.0  33.600000
5830477      2302955212            3352203                1711                     1711             Vital Signs                  Temperature             Temperature (C)               34.1      30.0         1017.0       2028.0         60.0  33.800000
5830713      2288344060            3352203                1741                     1741             Vital Signs                  Temperature             Temperature (C)               34.2      30.0         1023.0       2040.0         60.0  34.000000
5830731      2283249615            3352203                1771                     1771             Vital Signs                  Temperature             Temperature (C)               34.1      30.0         1026.0       2049.0         60.0  34.150000
5831372      2289540902            3352203                1801                     1801             Vital Signs                  Temperature             Temperature (C)               33.9      30.0         1023.0       2049.0         60.0  34.150000
5830725      2300504329            3352203                1831                     1831             Vital Signs                  Temperature             Temperature (C)               33.9      30.0         1017.0       2040.0         60.0  34.000000
5830784      2291412356            3352203                1861                     1861             Vital Signs                  Temperature             Temperature (C)               34.0      30.0         1017.0       2034.0         60.0  33.900000
5830082      2312080053            3352203                1882                     1882             Vital Signs                  Temperature             Temperature (C)               34.2      21.0          714.0       1731.0         51.0  33.941176
5829939      2308191776            3352203                1891                     1891             Vital Signs                  Temperature             Temperature (C)               34.3       9.0          307.8       1021.8         30.0  34.060000
5831428      2289735052            3352203                1921                     1921             Vital Signs                  Temperature             Temperature (C)               34.5      30.0         1029.0       1336.8         39.0  34.276923
5830164      2282433713            3352203                1951                     1951             Vital Signs                  Temperature             Temperature (C)               34.6      30.0         1035.0       2064.0         60.0  34.400000
5831289      2302994304            3352203                1981                     1981             Vital Signs                  Temperature             Temperature (C)               34.8      30.0         1038.0       2073.0         60.0  34.550000
5830214      2308397556            3352203                2011                     2011             Vital Signs                  Temperature             Temperature (C)               34.9      30.0         1044.0       2082.0         60.0  34.700000
5830890      2293420143            3352203                2041                     2041             Vital Signs                  Temperature             Temperature (C)               35.1      30.0         1047.0       2091.0         60.0  34.850000
5830003      2302246913            3352203                2071                     2071             Vital Signs                  Temperature             Temperature (C)               35.5      30.0         1053.0       2100.0         60.0  35.000000
5830359      2290841081            3352203                2101                     2101             Vital Signs                  Temperature             Temperature (C)               35.8      30.0         1065.0       2118.0         60.0  35.300000
5830170      2301348325            3352203                2131                     2131             Vital Signs                  Temperature             Temperature (C)               36.0      30.0         1074.0       2139.0         60.0  35.650000
5830299      2305029267            3352203                2161                     2161             Vital Signs                  Temperature             Temperature (C)               36.1      30.0         1080.0       2154.0         60.0  35.900000
5830779      2293496618            3352203                2191                     2191             Vital Signs                  Temperature             Temperature (C)               36.3      30.0         1083.0       2163.0         60.0  36.050000
5831095      2296446973            3352203                2221                     2221             Vital Signs                  Temperature             Temperature (C)               36.5      30.0         1089.0       2172.0         60.0  36.200000
5830428      2298272351            3352203                2251                     2251             Vital Signs                  Temperature             Temperature (C)               36.7      30.0         1095.0       2184.0         60.0  36.400000

In [146]:
myPredictorsDf

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,VTachy,VFib,Hypothermia
220,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,0,0,0
601,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,0,0,0
602,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,0,0,1
700,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,0,0,0
838,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200717,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,0,0,1
200731,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,0,0,1
200765,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,0,0,1
200844,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,0,0,0
200856,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,0,0,1

In [147]:
sorted(nurse_charting_df['nursingchartcelltypevalname'].drop_duplicates().to_list())

['Bedside Glucose',
 'CI',
 'CO',
 'CPP',
 'CVP',
 'Delirium Scale',
 'Delirium Score',
 'Electrolyte Replacement',
 'End Tidal CO2',
 'Eyes',
 'Fall Risk',
 'GCS Total',
 'Heart Rate',
 'IAP',
 'ICP',
 'Invasive BP Diastolic',
 'Invasive BP Mean',
 'Invasive BP Systolic',
 'Motor',
 'Non-Invasive BP Diastolic',
 'Non-Invasive BP Mean',
 'Non-Invasive BP Systolic',
 'O2 Admin Device',
 'O2 L/%',
 'O2 Saturation',
 'PA Diastolic',
 'PA Mean',
 'PA Systolic',
 'PAOP',
 'PR',
 'PVR',
 'PVRI',
 'Pain Goal',
 'Pain Score',
 'QRS',
 'QT',
 'QTc',
 'Respiratory Rate',
 'SV',
 'SVO2',
 'SVR',
 'SVRI',
 'Sedation Goal',
 'Sedation Scale',
 'Sedation Score',
 'Temperature (C)',
 'Temperature (F)',
 'Temperature Location',
 'Value',
 'Verbal']

In [62]:
nurse_charting_df['num_values'] = pd.to_numeric(nurse_charting_df.nursingchartvalue, errors='coerce')
myMasterGroupDf = nurse_charting_df[(nurse_charting_df.nursingchartentryoffset > 0) & (nurse_charting_df.nursingchartentryoffset < 360)].groupby(['patientunitstayid', 'nursingchartcelltypevalname'])
myMasterGroupBegin = nurse_charting_df.loc[myMasterGroupDf.nursingchartoffset.idxmin()]
myMasterGroupEnd = nurse_charting_df.loc[myMasterGroupDf.nursingchartoffset.idxmax()]
myMasterGroupMean = myMasterGroupDf.agg({'mean', 'min', 'max'})
myMasterGroupMean = myMasterGroupMean.num_values.reset_index()

/tmp/ipykernel_210/3011727309.py:5: FutureWarning: ['nursingchartcelltypecat', 'nursingchartcelltypevallabel', 'nursingchartvalue'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  myMasterGroupMean = myMasterGroupDf.agg({'mean', 'min', 'max'})

In [33]:
myMasterGroupMean

       patientunitstayid nursingchartcelltypevalname    max    min        mean
0                 142723                   GCS Total   11.0   11.0   11.000000
1                 142723                  Heart Rate  124.0   54.0   87.750000
2                 142723   Non-Invasive BP Diastolic   62.0   42.0   48.208333
3                 142723        Non-Invasive BP Mean   81.0   59.0   64.875000
4                 142723    Non-Invasive BP Systolic  103.0   82.0   91.083333
...                  ...                         ...    ...    ...         ...
48460            3353251                      O2 L/%  100.0  100.0  100.000000
48461            3353251               O2 Saturation  100.0   87.0   96.947368
48462            3353251            Respiratory Rate   34.0   24.0   25.105263
48463            3353251             Temperature (C)   33.4   32.9   33.071429
48464            3353251             Temperature (F)   92.1   91.2   91.528571

[48465 rows x 5 columns]

In [63]:
# for value in myMasterGroupBegin.nursingchartcelltypevalname.unique():
#     myDf = myMasterGroupBegin[myMasterGroupBegin.nursingchartcelltypevalname == value]
#     myPredictorsDf.drop(columns=[value], inplace=True)
#     myPredictorsDf = myPredictorsDf.merge(myDf[['patientunitstayid', 'nursingchartvalue']], on='patientunitstayid', how='left')
#     myPredictorsDf['first' + value] = myPredictorsDf.nursingchartvalue
#     myPredictorsDf.drop(columns=['nursingchartvalue'], inplace=True)

# for value in myMasterGroupEnd.nursingchartcelltypevalname.unique():
#     myDf = myMasterGroupEnd[myMasterGroupEnd.nursingchartcelltypevalname == value]
#     myPredictorsDf = myPredictorsDf.merge(myDf[['patientunitstayid', 'nursingchartvalue']], on='patientunitstayid', how='left')
#     myPredictorsDf['last' + value] = myPredictorsDf.nursingchartvalue
#     myPredictorsDf.drop(columns=['nursingchartvalue'], inplace=True)

for value in myMasterGroupMean.nursingchartcelltypevalname.unique():
    myDf = myMasterGroupMean[myMasterGroupMean.nursingchartcelltypevalname == value]
    myPredictorsDf = myPredictorsDf.merge(myDf[['patientunitstayid', 'max', 'min', 'mean']], on='patientunitstayid', how='left')
    myPredictorsDf['max' + value] = myPredictorsDf['max']
    myPredictorsDf['min' + value] = myPredictorsDf['min']
    myPredictorsDf['mean' + value] = myPredictorsDf['mean']
    myPredictorsDf.drop(columns=['max', 'min', 'mean'], inplace=True)

/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/3960265353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/3960265353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/3960265353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [64]:
myPredictorsDf.columns

Index(['patientunitstayid', 'gender', 'age', 'apacheadmissiondx',
       'admissionheight', 'hospitaladmittime24', 'hospitaladmitsource',
       'admissionweight', 'PEA', 'Asystole',
       ...
       'meanSVR', 'maxSVRI', 'minSVRI', 'meanSVRI', 'maxPAOP', 'minPAOP',
       'meanPAOP', 'maxPVRI', 'minPVRI', 'meanPVRI'],
      dtype='object', length=966)

In [148]:
gcs_df = nurse_charting_df[nurse_charting_df['nursingchartcelltypevalname']=='GCS Total']

In [149]:
motor_gcs_df = nurse_charting_df[nurse_charting_df.nursingchartcelltypevalname == 'Motor']

In [150]:
motor_gcs_df

,nursingchartid,patientunitstayid,nursingchartoffset,nursingchartentryoffset,nursingchartcelltypecat,nursingchartcelltypevallabel,nursingchartcelltypevalname,nursingchartvalue
37341,138827211,158800,8,89,Scores,Glasgow coma score,Motor,1
87295,174909972,168071,10585,10599,Scores,Glasgow coma score,Motor,6
93650,138825186,168324,108,216,Scores,Glasgow coma score,Motor,1
162074,138769012,192236,35510,35526,Scores,Glasgow coma score,Motor,4
171156,156847734,193911,10502,10577,Scores,Glasgow coma score,Motor,5
...,...,...,...,...,...,...,...,...
5844049,2285389238,3353251,2653,2653,Scores,Glasgow coma score,Motor,1
5844092,2303362635,3353251,10843,10843,Scores,Glasgow coma score,Motor,6
5844139,2298469311,3353251,764,764,Scores,Glasgow coma score,Motor,1
5844140,2288345711,3353251,15168,15168,Scores,Glasgow coma score,Motor,6
5844180,2300945253,3353251,15643,15643,Scores,Glasgow coma score,Motor,6

In [151]:
myGcsDf = gcs_df.sort_values(by=['patientunitstayid', "nursingchartoffset"])
myGcsDf['nursingchartoffset2'] = myGcsDf.nursingchartoffset
myGcsDf2 = myGcsDf.groupby('patientunitstayid').agg({'nursingchartoffset':'min', 'nursingchartoffset2': 'max'})
myGcsDfMin = myGcsDf.merge(myGcsDf2, on=['patientunitstayid', 'nursingchartoffset'], how='inner')
myGcsDfMax = myGcsDf.merge(myGcsDf2, on=['patientunitstayid', 'nursingchartoffset2'], how='inner')

In [152]:
myMGcsDf = motor_gcs_df.sort_values(by=['patientunitstayid', 'nursingchartoffset'])
myMGcsDf['nursingchartoffset2'] = myMGcsDf.nursingchartoffset
myMGcsDf2 = myMGcsDf.groupby('patientunitstayid').agg({'nursingchartoffset':'min', 'nursingchartoffset2': 'max'})
myMGcsDfMin = myMGcsDf.merge(myMGcsDf2, on=['patientunitstayid', 'nursingchartoffset'], how='inner')
myMGcsDfMax = myMGcsDf.merge(myMGcsDf2, on=['patientunitstayid', 'nursingchartoffset2'], how='inner')

In [158]:
myMGcsDfMax

,nursingchartid,patientunitstayid,nursingchartoffset_x,nursingchartentryoffset,nursingchartcelltypecat,nursingchartcelltypevallabel,nursingchartcelltypevalname,nursingchartvalue,nursingchartoffset2,nursingchartoffset_y
0,138827211,158800,8,89,Scores,Glasgow coma score,Motor,1,8,8
1,174909972,168071,10585,10599,Scores,Glasgow coma score,Motor,6,10585,10585
2,138825186,168324,108,216,Scores,Glasgow coma score,Motor,1,108,108
3,138769012,192236,35510,35526,Scores,Glasgow coma score,Motor,4,35510,35510
4,156847734,193911,10502,10577,Scores,Glasgow coma score,Motor,5,10502,10502
...,...,...,...,...,...,...,...,...,...,...
2929,2287942733,3351806,4566,4566,Scores,Glasgow coma score,Motor,1,4566,3132
2930,2291882680,3351912,130390,130390,Scores,Glasgow coma score,Motor,5,130390,2965
2931,2284258361,3352159,62,62,Scores,Glasgow coma score,Motor,1,62,62
2932,2311451473,3352727,3716,3716,Scores,Glasgow coma score,Motor,6,3716,2516
2933,2309514622,3353251,18529,18529,Scores,Glasgow coma score,Motor,6,18529,508

In [157]:
myPredictorsDf1 = myPredictorsDf

In [37]:
myPredictorsDf

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,...,QT,QTc,PA Mean,PA Diastolic,PA Systolic,Fall Risk,SVR,SVRI,PAOP,PVRI
0,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3401,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3402,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3403,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3404,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
myPredictorsDf = myPredictorsDf.merge(myGcsDfMin[['patientunitstayid', 'nursingchartentryoffset', 'nursingchartvalue']], on='patientunitstayid')
myPredictorsDf.rename(columns={'nursingchartentryoffset': 'FirstGCSTime', 'nursingchartvalue': 'FirstGCS'}, inplace=True)
myPredictorsDf =myPredictorsDf.merge(myGcsDfMax[['patientunitstayid', 'nursingchartentryoffset', 'nursingchartvalue']], on='patientunitstayid')
myPredictorsDf.rename(columns={'nursingchartentryoffset': 'LastGCSTime', 'nursingchartvalue': 'LastGCS'}, inplace=True)

In [159]:
myPredictorsDf = myPredictorsDf.merge(myMGcsDfMin[['patientunitstayid', 'nursingchartentryoffset', 'nursingchartvalue']], on='patientunitstayid', how='outer')
myPredictorsDf.rename(columns={'nursingchartentryoffset': 'FirstMGCSTime', 'nursingchartvalue': 'FirstMGCS'}, inplace=True)
myPredictorsDf =myPredictorsDf.merge(myMGcsDfMax[['patientunitstayid', 'nursingchartentryoffset', 'nursingchartvalue']], on='patientunitstayid', how='outer')
myPredictorsDf.rename(columns={'nursingchartentryoffset': 'LastMGCSTime', 'nursingchartvalue': 'LastMGCS'}, inplace=True)

In [37]:
file_path = database_folder+'lab.csv'
chunk_size = 1e6

# patient_unit_stay_ids = ca_patients_df['patientunitstayid']
df_chunks = []

num_chunks = 0
for chunk in pd.read_csv(file_path,chunksize=chunk_size):
    filtered_chunk = chunk[chunk['patientunitstayid'].isin(myIds[0])]
    df_chunks.append(filtered_chunk)
    if num_chunks % 10 == 0:
        print(f'Chunk {num_chunks} Processed.')
    num_chunks += 1
    del chunk

myLabs = pd.concat(df_chunks, ignore_index=True)
print('Processing finished.')

Chunk 0 Processed.
Chunk 10 Processed.
Chunk 20 Processed.
Chunk 30 Processed.
Processing finished.

In [39]:
myLabs

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
0,45551268,142723,-21,1,magnesium,1.700,1.7,mg/dL,mg/dL,18
1,51593737,142723,-21,3,MCH,27.300,27.3,pg,pg,-11
2,47238164,142723,105,1,lactate,5.700,5.7,mmol/L,mmol/L,133
3,47168398,142723,152,1,albumin,1.300,1.3,g/dL,g/dL,199
4,49725004,142723,891,2,Vancomycin - random,9.600,9.6,mcg/mL,mcg/mL,946
...,...,...,...,...,...,...,...,...,...,...
1293181,826720664,3353251,4049,4,bedside glucose,129.000,129,mg/dL,mg/dL,4049
1293182,822488872,3353251,1849,1,BUN,32.000,32,mg/dL,mg/dL,1894
1293183,829194475,3353251,310,7,pH,7.194,7.194,NaN,NaN,310
1293184,822355171,3353251,409,1,potassium,4.400,4.4,mmol/L,mmol/L,451
1293185,822488866,3353251,1849,1,anion gap,13.000,13,NaN,NaN,1894

In [22]:
myMasterGroupDf = myLabs[(myLabs.labresultoffset > 0) & (myLabs.labresultoffset < 240)].groupby(['patientunitstayid', 'labname'])
myMasterGroup = myLabs.loc[myMasterGroupDf.labresultoffset.idxmin()]
myMasterGroup

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
51,55622131,142723,105,3,-basos,0.000,0,%,%,132
77,55622134,142723,105,3,-eos,0.000,0,%,%,132
27,55622129,142723,105,3,-lymphs,2.000,2,%,%,132
65,55622140,142723,105,3,-monos,0.000,0,%,%,132
19,55622132,142723,105,3,-polys,98.000,98,%,%,132
...,...,...,...,...,...,...,...,...,...,...
1292680,827481900,3353251,69,4,bedside glucose,346.000,346,mg/dL,mg/dL,69
1293058,829742573,3353251,82,7,pH,7.161,7.161,NaN,NaN,82
1293106,829742572,3353251,82,7,paCO2,34.800,34.8,mm Hg,mmHg,82
1293118,829742571,3353251,82,7,paO2,136.000,136.0,mm Hg,mmHg,82
1292877,822499390,3353251,56,1,potassium,3.900,3.9,mmol/L,mmol/L,102

In [40]:
myLabs['num_values'] = pd.to_numeric(myLabs.labresultoffset, errors='coerce')
myMasterGroupDf = myLabs[(myLabs.labresultoffset > 0) & (myLabs.labresultoffset < 360)].groupby(['patientunitstayid', 'labname'])
myMasterGroupBegin = myLabs.loc[myMasterGroupDf.labresultoffset.idxmin()]
myMasterGroupEnd = myLabs.loc[myMasterGroupDf.labresultoffset.idxmax()]
myMasterGroupMean = myMasterGroupDf.agg({'mean', 'min', 'max'})
myMasterGroupMean = myMasterGroupMean.num_values.reset_index()

/tmp/ipykernel_210/742524077.py:5: FutureWarning: ['labresulttext', 'labmeasurenamesystem', 'labmeasurenameinterface'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  myMasterGroupMean = myMasterGroupDf.agg({'mean', 'min', 'max'})

In [46]:
myPredictorsDf.drop(columns=['labresult_x', 'labresult_y', 'first-basos'], inplace=True)

In [60]:
# for value in myMasterGroupBegin.labname.unique():
#     myDf = myMasterGroupBegin[myMasterGroupBegin.labname == value]
#     if value in myPredictorsDf.columns:
#         myPredictorsDf.drop(columns=[value], inplace=True)
#     myPredictorsDf = myPredictorsDf.merge(myDf[['patientunitstayid', 'labresult']], on='patientunitstayid', how='left')
#     myPredictorsDf['first' + value] = myPredictorsDf.labresult
#     myPredictorsDf.drop(columns=['labresult'], inplace=True)

# for value in myMasterGroupEnd.labname.unique():
#     myDf = myMasterGroupEnd[myMasterGroupEnd.labname == value]
#     myPredictorsDf = myPredictorsDf.merge(myDf[['patientunitstayid', 'labresult']], on='patientunitstayid', how='left')
#     myPredictorsDf['last' + value] = myPredictorsDf.labresult
#     myPredictorsDf.drop(columns=['labresult'], inplace=True)

for value in myMasterGroupMean.labname.unique():
    myDf = myMasterGroupMean[myMasterGroupMean.labname == value]
    myPredictorsDf = myPredictorsDf.merge(myDf[['patientunitstayid', 'max', 'min', 'mean']], on='patientunitstayid', how='left')
    myPredictorsDf['max' + value] = myPredictorsDf['max']
    myPredictorsDf['min' + value] = myPredictorsDf['min']
    myPredictorsDf['mean' + value] = myPredictorsDf['mean']
    myPredictorsDf.drop(columns=['max', 'min', 'mean'], inplace=True)

/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['mean' + value] = myPredictorsDf['mean']
/tmp/ipykernel_210/2382273120.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['max' + value] = myPredictorsDf['max']
/tmp/ipykernel_210/2382273120.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  myPredictorsDf['min' + value] = myPredictorsDf['min']
/tmp/ipykernel_210/2382273120.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [55]:
cols = myPredictorsDf.columns
for column in cols:
    if 'max' in column or 'min' in column or 'mean' in column:
        myPredictorsDf.drop(columns=[column], inplace=True)

In [61]:
myPredictorsDf

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,...,meanSite,maxCRP-hs,minCRP-hs,meanCRP-hs,maxPTT ratio,minPTT ratio,meanPTT ratio,maxWBC's in body fluid,minWBC's in body fluid,meanWBC's in body fluid
0,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3401,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3402,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3403,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3404,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# myDf = myMasterGroupMean[myMasterGroupMean.labname == 'GCS Total']
# myPredictorsDf.merge(myDf[['patientunitstayid', 'max', 'min', 'mean']], on='patientunitstayid', how='left')

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,...,lastWBC's in peritoneal fluid,lastANF/ANA,lastCarbamazepine,lastSite,lastCRP-hs,lastPTT ratio,lastWBC's in body fluid,max,min,mean
0,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3401,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3402,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3403,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3404,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
myLacta = myLabs[myLabs.labname.str.contains('lacta')]
myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)
myGroupLacta = myLacta.groupby('patientunitstayid').agg({'labresultoffset': 'min'})
myLacta = myGroupLacta.merge(myLacta, on=['patientunitstayid', 'labresultoffset'], how='inner')
myLacta.drop_duplicates(subset=['patientunitstayid', 'labresultoffset'], keep='first', inplace=True)
myPredictorsDf = myPredictorsDf.merge(myLacta[['patientunitstayid', 'labresult']], on='patientunitstayid', how='left')
myPredictorsDf.rename(columns={'labresult':'Lactate'}, inplace=True)

/tmp/ipykernel_173/108841860.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)

In [167]:
myLacta = myLabs[myLabs.labname.str.contains('tropo')]
myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)
myGroupLacta = myLacta.groupby('patientunitstayid').agg({'labresultoffset': 'min'})
myLacta = myLacta.merge(myGroupLacta, on=['patientunitstayid', 'labresultoffset'], how='inner')
myLacta.drop_duplicates(subset=['patientunitstayid', 'labresultoffset'], keep='first', inplace=True)
# myLacta.nunique()
myPredictorsDf = myPredictorsDf.merge(myLacta[['patientunitstayid', 'labresult']], on='patientunitstayid', how='left')
myPredictorsDf.rename(columns={'labresult':'Troponin'}, inplace=True)
# myPredictorsDf

/tmp/ipykernel_173/2619240775.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)

In [168]:
myLacta = myLabs[myLabs.labname.str.contains('pH')]
myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)
myGroupLacta = myLacta.groupby('patientunitstayid').agg({'labresultoffset': 'min'})
myLacta = myLacta.merge(myGroupLacta, on=['patientunitstayid', 'labresultoffset'], how='inner')
myLacta.drop_duplicates(subset=['patientunitstayid', 'labresultoffset'], keep='first', inplace=True)
# myLacta.nunique()
myPredictorsDf = myPredictorsDf.merge(myLacta[['patientunitstayid', 'labresult']], on='patientunitstayid', how='left')
myPredictorsDf.rename(columns={'labresult':'pH'}, inplace=True)

/tmp/ipykernel_173/3472696727.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)

In [169]:
myLacta = myLabs[myLabs.labname.str.contains('chloride')]
myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)
myGroupLacta = myLacta.groupby('patientunitstayid').agg({'labresultoffset': 'min'})
myLacta = myLacta.merge(myGroupLacta, on=['patientunitstayid', 'labresultoffset'], how='inner')
myLacta.drop_duplicates(subset=['patientunitstayid', 'labresultoffset'], keep='first', inplace=True)
# myLacta.nunique()
myPredictorsDf = myPredictorsDf.merge(myLacta[['patientunitstayid', 'labresult']], on='patientunitstayid', how='left')
myPredictorsDf.rename(columns={'labresult':'Chloride'}, inplace=True)

/tmp/ipykernel_173/10747074.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myLacta.sort_values(by=['patientunitstayid', 'labresultoffset'], inplace=True)

In [15]:
myPredictorsDf = pd.read_csv('eICUPredictorsDiag.csv')

/tmp/ipykernel_171/3248146962.py:1: DtypeWarning: Columns (14,16,41,51,63,65,66,76,80,89,99,111,113,114,124,128) have mixed types. Specify dtype option on import or set low_memory=False.
  myPredictorsDf = pd.read_csv('eICUPredictorsDiag.csv')

In [409]:
myPredictorsDf.drop(columns=['Unnamed: 0'], inplace=True)

In [380]:
myLabs[myLabs.labname.str.contains('')]

Empty DataFrame
Columns: [labid, patientunitstayid, labresultoffset, labtypeid, labname, labresult, labresulttext, labmeasurenamesystem, labmeasurenameinterface, labresultrevisedoffset]
Index: []

In [383]:
print(myLabs.groupby('labname').agg({'patientunitstayid':'count'}).to_string())

                              patientunitstayid
labname
-bands                                     2904
-basos                                    13438
-eos                                      14165
-lymphs                                   16225
-monos                                    16061
-polys                                    13294
24 h urine protein                          102
24 h urine urea nitrogen                     10
ALT (SGPT)                                13734
ANF/ANA                                       9
AST (SGOT)                                13712
Acetaminophen                               225
Amikacin - peak                               2
Amikacin - random                             8
Amikacin - trough                            11
BNP                                        1424
BUN                                       37078
Base Deficit                               3559
Base Excess                               20599
CPK                                        4244
CPK-MB                                     2974
CPK-MB INDEX                               1404
CRP                                         281
CRP-hs                                       19
Carbamazepine                                14
Carboxyhemoglobin                          4349
Cyclosporin                                   6
Device                                      334
Digoxin                                     205
ESR                                         190
Fe                                          342
Fe/TIBC Ratio                               170
Ferritin                                    302
FiO2                                      23824
Gentamicin - peak                             8
Gentamicin - random                          21
Gentamicin - trough                          29
HCO3                                      23629
HDL                                         626
HSV 1&2 IgG AB titer                          1
Hct                                       35065
Hgb                                       36451
LDH                                         681
LDL                                         451
LPM O2                                      418
Lidocaine                                    36
Lithium                                      15
MCH                                       28707
MCHC                                      30255
MCV                                       30264
MPV                                       23390
Methemoglobin                              4397
Mode                                         48
NAPA                                          3
O2 Content                                 2754
O2 Sat (%)                                20696
Oxyhemoglobin                              2089
PEEP                                      10447
PT                                        13107
PT - INR                                  13708
PTT                                       13995
PTT ratio                                   130
Peak Airway/Pressure                        297
Phenobarbital                                46
Phenytoin                                   305
Pressure Control                            378
Pressure Support                           1143
Procainamide                                  3
RBC                                       30473
RDW                                       28791
Respiratory Rate                           3176
Site                                         25
Spontaneous Rate                            379
T3                                           38
T3RU                                         13
T4                                           62
TIBC                                        221
TSH                                         996
TV                                        10148
Tacrolimus-FK506                            120
Temperature                                5669
Theophylline                                  8
Tobramycin - peak                             4
Tobramycin - random                          32
Tobramycin - trough                          13
Total CO2                                 10022
Vancomycin - peak                             1
Vancomycin - random                        1006
Vancomycin - trough                        1298
Vent Other                                  240
Vent Rate                                  4679
Vitamin B12                                 247
WBC x 1000                                30525
WBC's in body fluid                          43
WBC's in cerebrospinal fluid                 63
WBC's in peritoneal fluid                     8
WBC's in pleural fluid                       17
WBC's in synovial fluid                       1
WBC's in urine                              634
albumin                                   15870
alkaline phos.                            13532
ammonia                                     760
amylase                                     856
anion gap                                 29547
bedside glucose                          111982
bicarbonate                               34933
calcium                                   35667
cd 4                                          7
chloride                                  37774
cortisol                                    350
creatinine                                37215
direct bilirubin                           3442
ethanol                                     291
fibrinogen                                 1442
folate                                      189
free T4                                     346
glucose                                   39244
glucose - CSF                                74
haptoglobin                                 118
ionized calcium                            7453
lactate                                   11092
lipase                                     1336
magnesium                                 24269
myoglobin                                   139
pH                                        25487
paCO2                                     25949
paO2                                      25978
phosphate                                 18207
platelets x 1000                          30864
potassium                                 45334
prealbumin                                  487
prolactin                                    21
protein - CSF                                74
protein C                                    10
protein S                                    10
reticulocyte count                          101
salicylate                                  174
serum ketones                                19
serum osmolality                            553
sodium                                    42204
total bilirubin                           13665
total cholesterol                           656
total protein                             13569
transferrin                                 146
triglycerides                              1466
troponin - I                               6847
troponin - T                               1947
uric acid                                   222
urinary creatinine                          404
urinary osmolality                          215
urinary sodium                              450
urinary specific gravity                   2436

In [396]:
patients_df.hospitaldischargestatus

220         Alive
601       Expired
602       Expired
700         Alive
838         Alive
           ...
200717    Expired
200731    Expired
200765    Expired
200844    Expired
200856      Alive
Name: hospitaldischargestatus, Length: 3405, dtype: object

In [173]:
myPredictorsDf = myPredictorsDf.merge(patients_df[['patientunitstayid', 'hospitaldischargestatus']], on=['patientunitstayid'])
# myPredictorsDf.hospitaldischargestatus

In [174]:
myPredictorsDf

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,...,LastGCS,FirstMGCSTime,FirstMGCS,LastMGCSTime,LastMGCS,Lactate,Troponin,pH,Chloride,hospitaldischargestatus
0,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,...,15,NaN,NaN,NaN,NaN,5.7,0.28,7.170,86.0,Alive
1,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,3,NaN,NaN,NaN,NaN,5.7,NaN,7.230,103.0,Expired
2,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,4,NaN,NaN,NaN,NaN,4.8,NaN,7.360,118.0,Expired
3,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,...,15,NaN,NaN,NaN,NaN,NaN,NaN,7.440,105.0,Alive
4,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,...,15,NaN,NaN,NaN,NaN,1.1,31.24,7.360,103.0,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,...,3,NaN,NaN,NaN,NaN,10.9,0.05,6.966,103.0,Expired
3401,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,...,3,NaN,NaN,NaN,NaN,7.7,0.05,7.050,102.0,Expired
3402,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,...,15,2516.0,6,3716.0,6,10.6,0.22,7.302,106.0,Expired
3403,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,...,3,NaN,NaN,NaN,NaN,9.6,0.08,7.156,102.0,Expired
3404,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,...,15,508.0,1,18529.0,6,9.8,0.06,6.973,106.0,Alive

In [175]:
myPredictorsDf['DeathAtDischarge'] = myPredictorsDf.hospitaldischargestatus == 'Expired'
myPredictorsDf['DeathAtDischarge'] = myPredictorsDf['DeathAtDischarge'].astype(int)

In [176]:
# myPredictorsDf['LastGCS15'] = 0
myPredictorsDf['LastGCS15'] = (myPredictorsDf['LastGCS'] == '15').astype(int)

In [415]:
myPredictorsDf.LastGCS15.sum()

861

In [178]:
myPredictorsDf.loc[myPredictorsDf.age == '> 89', 'age'] = 89

In [179]:
myPredictorsDf.age = myPredictorsDf.age.astype(int)

In [52]:
myPredictorsDf[myPredictorsDf.columns[-1]]

RecursionError: maximum recursion depth exceeded in __instancecheck__

In [46]:
myPredictorsDf1.to_csv('eICUPredictorsDiag.csv', index=False)

In [58]:
myPredictorsDf.columns

Index(['patientunitstayid', 'gender', 'age', 'apacheadmissiondx',
       'admissionheight', 'hospitaladmittime24', 'hospitaladmitsource',
       'admissionweight', 'PEA', 'Asystole',
       ...
       'lastLidocaine', 'lastprolactin', 'last24 h urine urea nitrogen',
       'lastWBC's in peritoneal fluid', 'lastANF/ANA', 'lastCarbamazepine',
       'lastSite', 'lastCRP-hs', 'lastPTT ratio', 'lastWBC's in body fluid'],
      dtype='object', length=405)

In [171]:
myPredictorsDf.Hypothermia.sum()

788

In [170]:
myPredictorsDf

,patientunitstayid,gender,age,apacheadmissiondx,admissionheight,hospitaladmittime24,hospitaladmitsource,admissionweight,PEA,Asystole,...,LastGCSTime,LastGCS,FirstMGCSTime,FirstMGCS,LastMGCSTime,LastMGCS,Lactate,Troponin,pH,Chloride
0,142723,Female,68,Cardiac arrest (with or without respiratory ar...,165.1,21:48:29,Floor,50.30,0,0,...,1730,15,NaN,NaN,NaN,NaN,5.7,0.28,7.170,86.0
1,145204,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,-189,3,NaN,NaN,NaN,NaN,5.7,NaN,7.230,103.0
2,145205,Female,23,Cardiac arrest (with or without respiratory ar...,167.6,11:49:00,Emergency Department,64.50,0,0,...,6209,4,NaN,NaN,NaN,NaN,4.8,NaN,7.360,118.0
3,145830,Female,54,Cardiac arrest (with or without respiratory ar...,154.9,19:26:00,Floor,107.90,0,0,...,9762,15,NaN,NaN,NaN,NaN,NaN,NaN,7.440,105.0
4,146619,Male,74,Cardiac arrest (with or without respiratory ar...,182.8,02:11:00,Other Hospital,125.40,0,0,...,6709,15,NaN,NaN,NaN,NaN,1.1,31.24,7.360,103.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,3352445,Female,57,Cardiac arrest (with or without respiratory ar...,170.2,18:40:00,Emergency Department,113.40,0,1,...,7751,3,NaN,NaN,NaN,NaN,10.9,0.05,6.966,103.0
3401,3352512,Male,70,Cardiac arrest (with or without respiratory ar...,170.2,23:07:00,Emergency Department,104.30,0,0,...,6352,3,NaN,NaN,NaN,NaN,7.7,0.05,7.050,102.0
3402,3352727,Female,82,"Arrest, respiratory (without cardiac arrest)",162.6,23:04:00,Direct Admit,61.40,1,0,...,3716,15,2516.0,6,3716.0,6,10.6,0.22,7.302,106.0
3403,3353194,Female,51,Cardiac arrest (with or without respiratory ar...,170.2,07:17:00,Emergency Department,63.05,0,0,...,3413,3,NaN,NaN,NaN,NaN,9.6,0.08,7.156,102.0
3404,3353251,Male,73,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,Emergency Department,102.00,0,0,...,18529,15,508.0,1,18529.0,6,9.8,0.06,6.973,106.0

In [45]:
[x for x in one_hot.columns if 'emp' in x]

['treatment_empiric antibacterial coverage',
 'treatment_empiric antibacterial therapy',
 'treatment_pituitary and temperature regulation',
 'treatment_temporary',
 'treatment_wounds / temperature']